services:
    webserver:
        image: raazpuspa/larasail:8.4
        container_name: ${CONTAINER_PREFIX}
        ports:
            - '${FORWARD_APP_PORT}:80'
            - '${FORWARD_VITE_PORT}:${FORWARD_VITE_PORT}'
        environment:
            LARAVEL_SAIL: 1
            WWWUSER: '${WWWUSER:-1000}'
        volumes:
            - '.:/var/www/html'
        networks:
            - internal
        depends_on:
            - database
            - email

    database:
        image: mysql:8.0.31
        container_name: ${CONTAINER_PREFIX}_database
        ports:
            - '${FORWARD_DB_PORT}:3306'
        environment:
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - database:/var/lib/mysql
        networks:
            - internal

    email:
        image: axllent/mailpit
        container_name: ${CONTAINER_PREFIX}_email
        ports:
            - '${FORWARD_MAIL_PORT}:8025'
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    database:
        driver: local
